import { useState } from 'react'

export default function ResourceManager({ title, description, items, onCreate, fields }) {
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState(Object.fromEntries(fields.map((field) => [field.name, ''])))
  const [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); if (fields.some((field) => !form[field.name].trim())) { setError('Completa todos los campos obligatorios.'); return } try { await onCreate(form); setForm(Object.fromEntries(fields.map((field) => [field.name, '']))); setError(''); setOpen(false) } catch (createError) { setError(createError.message) } }
  return <section className="resource-page"><div className="resource-heading"><div><span className="eyebrow">Administracion</span><h2>{title}</h2><p>{description}</p></div><button className="primary-button" onClick={() => setOpen(true)}>＋ Registrar</button></div><div className="resource-list">{items.map((item) => <article className="resource-item" key={item.id}><div className="resource-icon">{title.includes('profesional') ? 'DR' : '⌂'}</div><div><strong>{item.name}</strong><span>{item.role || item.type}</span></div><i>Activo</i></article>)}</div>{open && <div className="modal-layer" onMouseDown={() => setOpen(false)}><form className="appointment-form resource-form" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><div className="form-header"><div><span className="eyebrow">Nuevo registro</span><h2>{title}</h2></div><button type="button" onClick={() => setOpen(false)}>×</button></div>{error && <div className="form-error">{error}</div>}{fields.map((field) => <label className="form-field" key={field.name}><span>{field.label}</span><input value={form[field.name]} onChange={(event) => setForm((current) => ({ ...current, [field.name]: event.target.value }))} placeholder={field.placeholder} /></label>)}<footer className="modal-footer"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancelar</button><button className="primary-button" type="submit">Guardar registro</button></footer></form></div>}</section>
}
